# Generated by Django 5.2.4 on 2025-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_birthday_member_email_member_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
